# Generated by Django 3.2.6 on 2021-08-31 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('team_name', models.CharField(max_length=50)),
                ('total_bid', models.FloatField(blank=True, null=True)),
                ('total_points', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_code', models.IntegerField()),
                ('fpl_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('web_name', models.CharField(max_length=25)),
                ('photo', models.CharField(blank=True, max_length=20, null=True)),
                ('now_cost', models.FloatField()),
                ('base_cost', models.FloatField()),
                ('minutes', models.FloatField()),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('goals_scored', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('clean_sheets', models.IntegerField(blank=True, null=True)),
                ('own_goals', models.IntegerField(blank=True, null=True)),
                ('penalties_saved', models.IntegerField(blank=True, null=True)),
                ('penalties_missed', models.IntegerField(blank=True, null=True)),
                ('yellow_cards', models.IntegerField(blank=True, null=True)),
                ('red_cards', models.IntegerField(blank=True, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('bonus', models.IntegerField(blank=True, null=True)),
                ('form', models.FloatField(blank=True, null=True)),
                ('selected_by_percent', models.FloatField(blank=True, null=True)),
                ('base_bid', models.FloatField()),
                ('current_bid', models.FloatField(blank=True, null=True)),
                ('bought', models.BooleanField(blank=True, default=False)),
                ('bought_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.manager')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=2, unique=True)),
                ('status_verbose', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_id', models.IntegerField()),
                ('position', models.CharField(max_length=4, unique=True)),
                ('position_verbose', models.CharField(max_length=20)),
                ('squad_select', models.IntegerField(blank=True, null=True)),
                ('squad_min_play', models.IntegerField(blank=True, null=True)),
                ('squad_max_play', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpl_id', models.IntegerField()),
                ('fpl_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=25)),
                ('short_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('type', models.IntegerField()),
                ('from_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_transfer', to='game.manager')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('to_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_transfer', to='game.manager')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw', models.IntegerField()),
                ('now_cost', models.FloatField(blank=True, null=True)),
                ('minutes', models.FloatField()),
                ('gw_points', models.IntegerField(blank=True, null=True)),
                ('goals_scored', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('clean_sheets', models.IntegerField(blank=True, null=True)),
                ('own_goals', models.IntegerField(blank=True, null=True)),
                ('penalties_saved', models.IntegerField(blank=True, null=True)),
                ('penalties_missed', models.IntegerField(blank=True, null=True)),
                ('yellow_cards', models.IntegerField(blank=True, null=True)),
                ('red_cards', models.IntegerField(blank=True, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('bonus', models.IntegerField(blank=True, null=True)),
                ('current_bid', models.FloatField(blank=True, null=True)),
                ('bought_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.manager')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='element_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.playertype'),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.playerstatus'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.team'),
        ),
        migrations.CreateModel(
            name='ManagerGameWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gw', models.IntegerField()),
                ('total_bid', models.FloatField(blank=True, null=True)),
                ('gw_points', models.FloatField(blank=True, default=0.0, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.manager')),
            ],
        ),
    ]
