# Generated by Django 3.2.6 on 2021-09-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_deadlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_gameweek', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='managergameweek',
            name='players',
            field=models.ManyToManyField(related_name='in_players', to='game.Player'),
        ),
        migrations.AddField(
            model_name='managergameweek',
            name='squads',
            field=models.ManyToManyField(related_name='in_squads', to='game.Player'),
        ),
        migrations.CreateModel(
            name='TransferOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(blank=True, null=True)),
                ('from_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_transfer_offer', to='game.manager')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('to_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_transfer_offer', to='game.manager')),
            ],
        ),
    ]
