# Generated by Django 3.2.6 on 2021-09-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210902_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managergameweek',
            old_name='squads',
            new_name='squad',
        ),
        migrations.RemoveField(
            model_name='managergameweek',
            name='players',
        ),
        migrations.AddField(
            model_name='managergameweek',
            name='benched',
            field=models.ManyToManyField(related_name='in_benches', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='transferoffer',
            name='from_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_sent', to='game.manager'),
        ),
        migrations.AlterField(
            model_name='transferoffer',
            name='to_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_received', to='game.manager'),
        ),
    ]
