# Generated by Django 3.2.6 on 2021-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210902_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferhistory',
            name='bid',
            field=models.FloatField(),
        ),
    ]
