# Generated by Django 3.2.6 on 2021-09-04 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_transferhistory_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_league_manager',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='parameters',
            name='is_auction_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_bid', models.FloatField()),
                ('highest_bid', models.FloatField(blank=True, default=0)),
                ('is_sold', models.BooleanField(blank=True, default=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('highest_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.manager')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
    ]
