# Generated by Django 3.2.6 on 2021-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210905_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='point_penalties',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
